# Generated by Django 3.1.7 on 2021-02-28 21:34

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='Brak opisu', max_length=255)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('miniature', models.FileField(default='defBlog.png', upload_to='image/%y/%m')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(default='brak kategorii', max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('blog_likes', models.ManyToManyField(related_name='blog_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
    ]
