# Generated by Django 3.1.7 on 2021-03-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jakubmeller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField(max_length=511)),
                ('image', models.FileField(default='blank.png', upload_to='image/%y/%m')),
                ('level', models.CharField(max_length=63)),
                ('section', models.IntegerField()),
            ],
        ),
    ]
